import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'
import prettierPlugin from 'eslint-plugin-prettier'
import simpleImportSort from 'eslint-plugin-simple-import-sort'
import tseslint from 'typescript-eslint'

export default [
  {
    ignores: [
      'node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      'packages/omnivore-polish/**', // Has its own ESLint 9 config
      'packages/web-vite/**', // Has its own ESLint 9 config
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'simple-import-sort': simpleImportSort,
      prettier: prettierPlugin,
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Prettier integration
      ...prettierConfig.rules,
      'prettier/prettier': 'error',

      // Import sorting
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',

      // Code quality rules from .eslintrc.base.json
      'arrow-body-style': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-const': 'warn',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'consistent-this': 'error',
      curly: ['error', 'all'],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
      'dot-notation': 'warn',
      eqeqeq: 'error',
      'for-direction': 'error',
      'global-require': 'warn',
      'guard-for-in': 'warn',
      'handle-callback-err': 'warn',
      'id-blacklist': 'error',
      'init-declarations': 'warn',
      'lines-around-directive': 'error',
      'lines-between-class-members': ['warn', 'always'],
      'max-depth': ['error', 4],
      'max-nested-callbacks': ['error', 4],
      'max-params': ['error', 11],
      'newline-before-return': 'warn',
      'no-array-constructor': 'error',
      'no-await-in-loop': 'warn',
      'no-caller': 'error',
      'no-catch-shadow': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': 'warn',
      'no-empty-function': 'off',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-loop-func': 'warn',
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'warn',
      'no-native-reassign': 'error',
      'no-proto': 'error',
      'no-prototype-builtins': 'off',
      'no-restricted-globals': 'error',
      'no-restricted-imports': 'error',
      'no-restricted-modules': 'error',
      'no-restricted-properties': 'error',
      'no-restricted-syntax': 'error',
      'no-return-await': 'warn',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-tabs': 'error',
      'no-template-curly-in-string': 'error',
      'no-undef-init': 'warn',
      'no-undefined': 'warn',
      '@typescript-eslint/prefer-nullish-coalescing': 'warn',
      '@typescript-eslint/prefer-optional-chain': 'error',
      '@typescript-eslint/no-unnecessary-condition': [
        'warn',
        { allowConstantLoopConditions: true },
      ],
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-use-before-define': [
        'warn',
        {
          functions: false,
        },
      ],
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'off',
      'no-useless-escape': 'warn',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'prefer-promise-reject-errors': 'warn',
      'prefer-rest-params': 'error',
      'prefer-template': 'warn',
      radix: 'warn',
      'symbol-description': 'error',
      'vars-on-top': 'error',
      yoda: 'error',
      'class-methods-use-this': 'off',
      '@typescript-eslint/no-empty-interface': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'error',
    },
  },
  {
    files: ['**/*.spec.ts', '**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'warn',
      'no-console': 'off',
    },
  },
]
